In [1]:
import torch
from torch import nn

In [2]:
net = nn.Sequential(nn.Linear(2, 8), nn.ReLU(), nn.Linear(8, 1))
x = torch.rand(2, 2)
net(x)

tensor([[-0.0374],
        [ 0.0349]], grad_fn=<AddmmBackward>)

In [6]:
net[0].state_dict()

OrderedDict([('weight',
              tensor([[ 0.2280, -0.5475],
                      [ 0.0953, -0.3233],
                      [ 0.1200,  0.5097],
                      [-0.0754, -0.6104],
                      [-0.4888,  0.1375],
                      [-0.0336,  0.1084],
                      [-0.0892,  0.4468],
                      [ 0.0112,  0.5701]])),
             ('bias',
              tensor([ 0.4042,  0.3410, -0.1909,  0.1726,  0.6812, -0.5554,  0.0605,  0.3875]))])

In [7]:
net.state_dict()

OrderedDict([('0.weight',
              tensor([[ 0.2280, -0.5475],
                      [ 0.0953, -0.3233],
                      [ 0.1200,  0.5097],
                      [-0.0754, -0.6104],
                      [-0.4888,  0.1375],
                      [-0.0336,  0.1084],
                      [-0.0892,  0.4468],
                      [ 0.0112,  0.5701]])),
             ('0.bias',
              tensor([ 0.4042,  0.3410, -0.1909,  0.1726,  0.6812, -0.5554,  0.0605,  0.3875])),
             ('2.weight',
              tensor([[ 0.1270,  0.2748, -0.2906, -0.3182, -0.0390, -0.0030, -0.3150,  0.1284]])),
             ('2.bias', tensor([-0.0765]))])

In [8]:
net[0].weight

Parameter containing:
tensor([[ 0.2280, -0.5475],
        [ 0.0953, -0.3233],
        [ 0.1200,  0.5097],
        [-0.0754, -0.6104],
        [-0.4888,  0.1375],
        [-0.0336,  0.1084],
        [-0.0892,  0.4468],
        [ 0.0112,  0.5701]], requires_grad=True)

In [11]:
net[0].weight.grad is None

True

In [12]:
net[0].weight.data

tensor([[ 0.2280, -0.5475],
        [ 0.0953, -0.3233],
        [ 0.1200,  0.5097],
        [-0.0754, -0.6104],
        [-0.4888,  0.1375],
        [-0.0336,  0.1084],
        [-0.0892,  0.4468],
        [ 0.0112,  0.5701]])

In [15]:
for param in net.parameters():
    print(param)

Parameter containing:
tensor([[ 0.2280, -0.5475],
        [ 0.0953, -0.3233],
        [ 0.1200,  0.5097],
        [-0.0754, -0.6104],
        [-0.4888,  0.1375],
        [-0.0336,  0.1084],
        [-0.0892,  0.4468],
        [ 0.0112,  0.5701]], requires_grad=True)
Parameter containing:
tensor([ 0.4042,  0.3410, -0.1909,  0.1726,  0.6812, -0.5554,  0.0605,  0.3875],
       requires_grad=True)
Parameter containing:
tensor([[ 0.1270,  0.2748, -0.2906, -0.3182, -0.0390, -0.0030, -0.3150,  0.1284]],
       requires_grad=True)
Parameter containing:
tensor([-0.0765], requires_grad=True)


In [16]:
for name, param in net.named_parameters():
    print(name, param)

0.weight Parameter containing:
tensor([[ 0.2280, -0.5475],
        [ 0.0953, -0.3233],
        [ 0.1200,  0.5097],
        [-0.0754, -0.6104],
        [-0.4888,  0.1375],
        [-0.0336,  0.1084],
        [-0.0892,  0.4468],
        [ 0.0112,  0.5701]], requires_grad=True)
0.bias Parameter containing:
tensor([ 0.4042,  0.3410, -0.1909,  0.1726,  0.6812, -0.5554,  0.0605,  0.3875],
       requires_grad=True)
2.weight Parameter containing:
tensor([[ 0.1270,  0.2748, -0.2906, -0.3182, -0.0390, -0.0030, -0.3150,  0.1284]],
       requires_grad=True)
2.bias Parameter containing:
tensor([-0.0765], requires_grad=True)


In [17]:
def init_normal(m):
    if isinstance(m, nn.Linear):
        nn.init.normal_(m.weight, mean=0, std=0.01)
        nn.init.zeros_(m.bias)

net.apply(init_normal)

for name, param in net.named_parameters():
    print(name, param)

0.weight Parameter containing:
tensor([[-0.0014,  0.0077],
        [-0.0047, -0.0036],
        [-0.0098, -0.0070],
        [-0.0022,  0.0054],
        [-0.0095,  0.0160],
        [-0.0008, -0.0071],
        [-0.0087,  0.0076],
        [-0.0128, -0.0056]], requires_grad=True)
0.bias Parameter containing:
tensor([0., 0., 0., 0., 0., 0., 0., 0.], requires_grad=True)
2.weight Parameter containing:
tensor([[ 0.0006,  0.0025, -0.0010,  0.0043, -0.0064, -0.0099,  0.0049,  0.0002]],
       requires_grad=True)
2.bias Parameter containing:
tensor([0.], requires_grad=True)
